### 🌍 Base Environment Variables
@baseUrl = http://localhost:3000
@contentType = application/json
@token = {{signup.response.body.data.jwtToken}} 
@token = {{login.response.body.data.jwtToken}} 


### SIGNUP - Signup user
# @name signup
POST {{baseUrl}}/auth/signup
Content-Type: {{contentType}}

{
  "name":"John",
  "email": "john@example.com",
  "password": "123456"
}

### LOGIN - Login user
# @name login
POST {{baseUrl}}/auth/login
Content-Type: {{contentType}}

{
  "email": "john@example.com",
  "password": "123456"
}

### LOGOUT - Logout user
# @name logout
POST {{baseUrl}}/auth/logout
Authorization: Bearer {{token}}
Content-Type: {{contentType}}


### PROFILE — Get logged-in user's info
# @name profile
GET {{baseUrl}}/auth/profile
Authorization: Bearer {{token}}
Content-Type: {{contentType}}

### CREATE POST - create a new post
# @name createPost
POST {{baseUrl}}/posts
Authorization: Bearer {{token}}
Content-Type: {{contentType}}

{
  "title": "third post",
  "content": "lorem ipsum"
}

### GET POSTS - get posts by pagination
# @name getPosts
GET {{baseUrl}}/posts?take=20&page=1
Authorization: Bearer {{token}}
Content-Type: {{contentType}}

### GET POST - get post by id
# @name getPost
GET {{baseUrl}}/posts/4
Authorization: Bearer {{token}}
Content-Type: {{contentType}}

### ARCHIVE POST - archive post by id
# @name getPost
POST  {{baseUrl}}/posts/archive/18
Authorization: Bearer {{token}}
Content-Type: {{contentType}}


### FOLLOW USER - follow a specific user
# @name followUser
POST  {{baseUrl}}/users/follow/4
Authorization: Bearer {{token}}
Content-Type: {{contentType}}

### UNFOLLOW USER - unfollow a specific user
# @name followUser
POST  {{baseUrl}}/users/unfollow/4
Authorization: Bearer {{token}}
Content-Type: {{contentType}}

### UNFOLLOW USER - unfollow a specific user
# @name followUser
GET  {{baseUrl}}/users/counts
Authorization: Bearer {{token}}
Content-Type: {{contentType}}





