services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: url_short_app
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - backend

  redis:
    container_name: redis
    image: redis:6.2-alpine
    restart: unless-stopped
    volumes:
      - redis_data:/data
    ports:
      - 6379:6379
    networks:
      - backend

  neo4j:
    container_name: neo4j
    image: neo4j:community
    ports:
      - '7474:7474'
      - '7687:7687'
    environment:
      - NEO4J_AUTH=neo4j/password
      - NEO4J_PLUGINS='["graph-data-science"]'
    volumes:
      - neo4j_data:/data
    networks:
      - backend

  nats:
    container_name: nats
    image: nats:2.10-alpine
    command: ['-js', '-m', '8222', '-sd', '/data']
    ports:
      - '4222:4222'
      - '8222:8222'
    volumes:
      - nats_data:/data
    networks:
      - backend

  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch:8.12.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - '9200:9200'
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - backend

  apollo-router:
    image: ghcr.io/apollographql/router:v1.38.0
    ports:
      - '4000:4000'
    command:
      ['--dev', '-c', 'config/router.yaml', '-s', 'schema/supergraph.graphql', '--log', 'info']
    volumes:
      - ./libs/shared/src/graphql/schema/supergraph.graphql:/dist/schema/supergraph.graphql
      - ./router/router.yaml:/dist/config/router.yaml
    networks:
      - backend

volumes:
  mysql_data:
  redis_data:
  neo4j_data:
  nats_data:
  elasticsearch_data:

networks:
  backend:
    driver: bridge
