services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: url_short_app
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - backend

  redis:
    container_name: redis
    image: redis:6.2-alpine
    restart: unless-stopped
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - 6379:6379
    networks:
      - backend

  apollo-router:
    image: ghcr.io/apollographql/router:v1.38.0
    ports:
      - '4000:4000'
    command:
      ['--dev', '-c', 'config/router.yaml', '-s', 'schema/supergraph.graphql', '--log', 'info']
    volumes:
      - ./libs/shared/src/graphql/schema/supergraph.graphql:/dist/schema/supergraph.graphql
      - ./router/router.yaml:/dist/config/router.yaml
    networks:
      - backend

volumes:
  mysql_data:
  redis_data:

networks:
  backend:
    driver: bridge
