CREATE DATABASE IF NOT EXISTS auth;

CREATE DATABASE IF NOT EXISTS posts;

CREATE DATABASE IF NOT EXISTS social;

GRANT ALL PRIVILEGES ON auth.* TO 'user' @'%';

GRANT ALL PRIVILEGES ON posts.* TO 'user' @'%';

GRANT ALL PRIVILEGES ON social.* TO 'user' @'%';

FLUSH PRIVILEGES;